=== UnalSoft/elite-fle/docs/texte11.dtd
<!ELEMENT DOCUMENTTEXTE (ENTETE, CONTENU)>
	<!ATTLIST DOCUMENTTEXTE id_doc ID #REQUIRED>
	<!ELEMENT ENTETE (titre_doc, auteur, source, date, type, niveau)>
    		<!ELEMENT titre_doc (#PCDATA)>
    		<!ELEMENT auteur (#PCDATA)>
    		<!ELEMENT source (#PCDATA)>
    			<!ATTLIST source type (magazine | journal | livre | internet | roman | inconnu) #REQUIRED>
   			<!ATTLIST source periodicite (hebdomadaire | journaliere | mensuelle | bimensuelle | annuelle | inconnue) #IMPLIED>
    		<!ELEMENT date (#PCDATA)>
    		<!ELEMENT type (#PCDATA)>
    		<!ELEMENT niveau (#PCDATA)>
    		<!ELEMENT activite (#PCDATA)>
  	<!ELEMENT CONTENU (titre?, (sous-titre?, paragraphe)*)>
    		<!ELEMENT titre (phrase+)>
    		<!ELEMENT sous-titre (phrase+)>
    		<!ELEMENT paragraphe (phrase+ | element)*>
      		<!ELEMENT phrase (#PCDATA | prop | element)*>
      			<!ATTLIST phrase type (simple | complexe) #REQUIRED>
	  	<!ELEMENT ellipse EMPTY>
          	<!ELEMENT prop (#PCDATA | referent | coreferent | element | prop)*>
		<!ELEMENT referent (#PCDATA | element)*>
		<!ELEMENT coreferent (#PCDATA | element)*>
		<!ELEMENT element (#PCDATA)*>
	      		<!ATTLIST prop type (principale | independante | subordonnee | averbale | incise) #REQUIRED>
              		<!ATTLIST prop sous-type (principale | participiale | completive | coordonnee | relative | juxtaposee | verbale | infinitive | conjonctive | averbale) #IMPLIED>
              		<!ATTLIST element type (DETIFS | NCFS | ADJSIG | PDS | VINDP3S |DETIMS | NCMS | ADV |VINF | DETDPIG | NCMP | PREP | DETDMS | NCFP | ADJFP | VINDP3P | ADJMP | PCTFORTE | DETDFS | ADJORD | DETPOSS | PPER3P | PPER3S | ADJFS | NCSIG | PCTFAIB | ADJNUM | NCMIN | PRI | NPFS | COO | ADJMS | NPI | NCHMS | SUB | NCFIN | ADJIND | VCONP3S | VPARPMS | NCPIG | NPMS | DETDEM | PIPIG | VPARPMP | VPARPFS | VPARPRES | PIMS | VINDF3S | ADJPIG | NPFIN | NPSIG | NPHSIG | VINDI3P | NPMIN | VINDI3S |PIMP | VPARPFP | PPER2P | VINDP2P | PIFP | NCI | PDP | ADJINT | PPER1P | VINDF2P | ADJINV | PII | VIMPP2P | VSUBP3S | VINDF3P | VINDPS3S | INT | PISIG | VINDPS3P | PPER2S | PPER1S | VINDI1P | VINDP2S | VINDP1S | ADJMIN | VIMPP1P | PRFS | PRMS | VIMPP2S | VCONP3P | PIFS | VINDP1P | ADJHFS | ADJHMS | VINDI2S | ELLIP) #REQUIRED>
			<!ATTLIST element cat (NC | V | DETD | ADJ | PPER | DETI | NP | PD | PI | PR) #IMPLIED>
			<!ATTLIST element mode (INF | IND | CON | PAR | IMP | SUB) #IMPLIED>
			<!ATTLIST element temps (P | F | PRES | I | PS) #IMPLIED>
			<!ATTLIST element pers (1 | 2 | 3) #IMPLIED>
			<!ATTLIST element genre (M | F | I) #IMPLIED>
			<!ATTLIST element nombre (S | P | I) #IMPLIED>
			<!ATTLIST referent type (Nom) #IMPLIED>
			<!ATTLIST referent sous-type (GN) #IMPLIED>
			<!ATTLIST referent idn ID #REQUIRED>
			<!ATTLIST coreferent type (Nom | Pron) #IMPLIED>
			<!ATTLIST coreferent sous-type (GN | COD | Pers | Rel | N | Compl | Pronom) #IMPLIED>
			<!ATTLIST coreferent classe (fidele | infidele | determinative | totale | partielle | integrante | associative) #IMPLIED>
			<!ATTLIST coreferent idn ID #REQUIRED>
			<!ATTLIST coreferent chaine IDREF #REQUIRED>
			<!ATTLIST coreferent position (Anaphore) #IMPLIED>
			<!ATTLIST coreferent reference IDREF #REQUIRED>

=== UnalSoft/elite-fle/docs/texte_corefB105test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DOCUMENTTEXTE SYSTEM "texte11.dtd">
<DOCUMENTTEXTE id_doc="B105">
<ENTETE>
<titre_doc>Les Thibault, tome 1, le cahier gris (fragment)</titre_doc>
<auteur>Roger Martin du Gard</auteur>
<source type="roman" periodicite="inconnue">Livre numérisé</source>
<date>1922</date>
<type>Narrative et dialogue</type>
<niveau>B1-CECR</niveau>
</ENTETE>
<CONTENU>

<paragraphe>
<phrase type="complexe"><prop type="independante" sous-type="juxtaposee"><element type="DETDMS" cat="DETD" genre="M" nombre="S">Au</element> <element type="NCMS" cat="NC" genre="M" nombre="S">coin</element> <element type="PREP">de</element> <element type="DETDFS" cat="DETD" genre="F" nombre="S">la</element> <element type="NCFS" cat="NC" genre="F" nombre="S">rue</element> <element type="PREP">de</element> <element type="NPMS" cat="NP" genre="M" nombre="S">Vaugirard</element><element type="PCTFAIB">,</element> <element type="SUB">comme</element> <element type="PPER3P" cat="PPER" pers="3" nombre="P">ils</element> <element type="VINDI3P" cat="V" mode="IND" temps="I" pers="3" nombre="P">longeaient</element> <element type="ADV">déjà</element> <element type="DETDPIG" cat="DETD" genre="I" nombre="P">les</element> <element type="NCMP" cat="NC" genre="M" nombre="P">bâtiments</element> <element type="PREP">de</element> <element type="DETDFS" cat="DETD" genre="F" nombre="S">l’</element><element type="NCFS" cat="NC" genre="F" nombre="S">École</element><element type="PCTFAIB">,</element></prop> <prop type="independante" sous-type="juxtaposee"><referent type="Nom" sous-type="GN" idn="r1"><element type="NCMS" cat="NC" genre="M" nombre="S">M.</element> <element type="NPMIN" cat="NP" genre="M" nombre="I">Thibault</element></referent><element type="PCTFAIB">,</element> <coreferent type="Pron" sous-type="Rel" classe="totale" idn="c1" chaine="r1" position="Anaphore" reference="r1"><element type="PRI">qui</element></coreferent> <element type="PREP">pendant</element> <element type="DETDMS" cat="DETD" genre="M" nombre="S">le</element> <element type="NCMS" cat="NC" genre="M" nombre="S">trajet</element> <element type="ADV">n’</element><element type="VINDI3S" cat="V" mode="IND" temps="I" pers="3" nombre="S">avait</element> <element type="ADV">pas</element> <element type="VPARPMS" cat="V" mode="PAR" temps="P" genre="M" nombre="S">adressé</element> <element type="DETDFS" cat="DETD" genre="F" nombre="S">la</element> <element type="NCFS" cat="NC" genre="F" nombre="S">parole</element> <element type="PREP">à</element> <coreferent type="Nom" sous-type="GN" classe="infidele" idn="c2" chaine="r2" position="Cataphore" reference="r2"><element type="DETPOSS">son</element> <element type="NCMS" cat="NC" genre="M" nombre="S">fils</element></coreferent><element type="PCTFAIB">,</element></prop> <prop type="independante" sous-type="juxtaposee"><coreferent type="Pron" sous-type="Pronom" classe="totale" idn="c3" chaine="r1" position="Anaphore" reference="r1"><element type="PPER3S" cat="PPER" pers="3" nombre="S">s’</element></coreferent><element type="VINDPS3S" cat="V" mode="IND" temps="PS" pers="3" nombre="S">arrêta</element> <element type="ADV">brusquement</element></prop> <element type="PCTFORTE">:</element></phrase> 
</paragraphe>
<paragraphe>
<phrase type="simple">– « <prop type="independante" sous-type="verbale"><element type="INT">Ah</element><element type="PCTFAIB">,</element> <element type="DETDEM">cette</element> <element type="NCFS" cat="NC" genre="F" nombre="S">fois</element><element type="PCTFAIB">,</element> <referent type="Nom" sous-type="NP" idn="r2"><element type="NPMS" cat="NP" genre="M" nombre="S">Antoine</element></referent><element type="PCTFAIB">,</element> <element type="ADV">non</element><element type="PCTFAIB">,</element> <element type="DETDEM">cette</element> <element type="NCFS" cat="NC" genre="F" nombre="S">fois</element><element type="PCTFAIB">,</element> <element type="PDS" cat="PD" nombre="S">ça</element> <element type="VINDP3S" cat="V" mode="IND" temps="P" pers="3" nombre="S">dépasse</element></prop> <element type="PCTFORTE">!</element> »</phrase> 
<phrase type="simple"><prop type="independante" sous-type="verbale"><coreferent type="Nom" sous-type="GN" classe="infidele" idn="c4" chaine="r2" position="Anaphore" reference="r2"><element type="DETDMS" cat="DETD" genre="M" nombre="S">Le</element> <element type="ADJMS" cat="ADJ" genre="M" nombre="S">jeune</element> <element type="NCMS" cat="NC" genre="M" nombre="S">homme</element></coreferent> <element type="ADV">ne</element> <element type="VINDPS3S" cat="V" mode="IND" temps="PS" pers="3" nombre="S">répondit</element> <element type="ADV">pas</element></prop><element type="PCTFORTE">.</element></phrase> 
</paragraphe>
<paragraphe>
<phrase type="simple"><prop type="independante" sous-type="verbale"><element type="DETDFS" cat="DETD" genre="F" nombre="S">L’</element><element type="NCFS" cat="NC" genre="F" nombre="S">École</element> <element type="VINDI3S" cat="V" mode="IND" temps="I" pers="3" nombre="S">était</element> <element type="VPARPFS" cat="V" mode="PAR" temps="P" genre="F" nombre="S">fermée</element></prop><element type="PCTFORTE">.</element></phrase> 
<phrase type="complexe"><prop type="independante" sous-type="coordonnee"><element type="PDS" cat="PD" nombre="S">C’</element><element type="VINDI3S" cat="V" mode="IND" temps="I" pers="3" nombre="S">était</element> <element type="NCMS" cat="NC" genre="M" nombre="S">dimanche</element><element type="PCTFAIB">,</element></prop> <prop type="independante" sous-type="coordonnee"><element type="COO">et</element> <element type="PPER3S" cat="PPER" pers="3" nombre="S">il</element> <element type="VINDI3S" cat="V" mode="IND" temps="I" pers="3" nombre="S">était</element> <element type="ADJNUM">neuf</element> <element type="NCFP" cat="NC" genre="F" nombre="P">heures</element> <element type="DETDMS" cat="DETD" genre="M" nombre="S">du</element> <element type="NCMS" cat="NC" genre="M" nombre="S">soir</element></prop><element type="PCTFORTE">.</element></phrase> 
<phrase type="simple"><prop type="independante" sous-type="verbale"><referent type="Nom" sous-type="GN" idn="r3"><element type="DETIMS" cat="DETI" genre="M" nombre="S">Un</element> <element type="NCMS" cat="NC" genre="M" nombre="S">portier</element></referent> <element type="VINDPS3S" cat="V" mode="IND" temps="PS" pers="3" nombre="S">entrouvrit</element> <element type="DETDMS" cat="DETD" genre="M" nombre="S">le</element> <element type="NCMS" cat="NC" genre="M" nombre="S">guichet</element></prop><element type="PCTFORTE">.</element></phrase> 
</paragraphe>
<paragraphe>
<phrase type="complexe">– « <prop type="subordonnee" sous-type="principale"><element type="VINDP2P" cat="V" mode="IND" temps="P" pers="2" nombre="P">Savez</element><coreferent type="Pron" sous-type="Pers" classe="totale" idn="c5" chaine="r3" position="Anaphore" reference="r3"><element type="PPER2P" cat="PPER" pers="2" nombre="P">-vous</element></coreferent></prop> <prop type="subordonnee" sous-type="relative"><element type="PRI">où</element> <element type="VINDP3S" cat="V" mode="IND" temps="P" pers="3" nombre="S">est</element> <coreferent type="Nom" sous-type="GN" classe="infidele" idn="c6" chaine="r5" position="Cataphore" reference="c23"><element type="DETPOSS">mon</element> <element type="NCMS" cat="NC" genre="M" nombre="S">frère</element></coreferent></prop> <element type="PCTFORTE">?</element> »</phrase> 
<phrase type="simple"><prop type="independante" sous-type="verbale"><element type="VINDPS3S" cat="V" mode="IND" temps="PS" pers="3" nombre="S">cria</element> <coreferent type="Nom" sous-type="NP" classe="fidele" idn="c7" chaine="r2" position="Anaphore" reference="c4"><element type="NPMS" cat="NP" genre="M" nombre="S">Antoine</element></coreferent></prop><element type="PCTFORTE">.</element></phrase> 
</paragraphe>
<paragraphe>
<phrase type="simple"><prop type="independante" sous-type="verbale"><coreferent type="Nom" sous-type="GN" classe="infidele" idn="c8" chaine="r3" position="Anaphore" reference="c5"><element type="DETDMS" cat="DETD" genre="M" nombre="S">L’</element><element type="PISIG">autre</element></coreferent> <element type="VINDPS3S" cat="V" mode="IND" temps="PS" pers="3" nombre="S">écarquilla</element> <element type="DETDPIG" cat="DETD" genre="I" nombre="P">les</element> <element type="NCMP" cat="NC" genre="M" nombre="P">yeux</element></prop><element type="PCTFORTE">.</element></phrase> 
<phrase type="simple"><prop type="independante" sous-type="verbale"><coreferent type="Nom" sous-type="GN" classe="fidele" idn="c9" chaine="r1" position="Anaphore" reference="r1"><element type="NCMS" cat="NC" genre="M" nombre="S">M.</element> <element type="NPMIN" cat="NP" genre="M" nombre="I">Thibault</element></coreferent> <element type="VINDPS3S" cat="V" mode="IND" temps="PS" pers="3" nombre="S">frappa</element> <element type="DETDMS" cat="DETD" genre="M" nombre="S">du</element> <element type="NCMS" cat="NC" genre="M" nombre="S">pied</element></prop><element type="PCTFORTE">.</element></phrase> 
</paragraphe>
<paragraphe>
<phrase type="simple">– « <prop type="independante" sous-type="verbale"><element type="VIMPP2P" cat="V" mode="IMP" temps="P" pers="2" nombre="P">Allez</element> <element type="VINF" cat="V" mode="INF">chercher</element> <referent type="Nom" sous-type="GN" idn="r4"><element type="DETDMS" cat="DETD" genre="M" nombre="S">l’</element><element type="NCMS" cat="NC" genre="M" nombre="S">abbé</element> <element type="NPMS" cat="NP" genre="M" nombre="S">Binot</element></referent></prop><element type="PCTFORTE">.</element> »</phrase> 
</paragraphe>
<paragraphe>
